# Generated by Django 3.2.dev20200624211641 on 2020-06-30 19:15

import Accounts.enums.UsersSex
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('flat_number', models.CharField(max_length=10, null=True)),
                ('postal_code', models.CharField(max_length=6, null=True)),
                ('sex', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Man', 'Man'), ('Woman', 'Woman')], enum_class=Accounts.enums.UsersSex.Sex, max_length=5)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
